# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.by_stock_code = QtWidgets.QGroupBox(self.centralwidget)
        self.by_stock_code.setGeometry(QtCore.QRect(10, 10, 671, 91))
        self.by_stock_code.setObjectName("by_stock_code")
        self.btn_search = QtWidgets.QPushButton(self.by_stock_code)
        self.btn_search.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.btn_search.setObjectName("btn_search")
        self.input_stock_code = QtWidgets.QLineEdit(self.by_stock_code)
        self.input_stock_code.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.input_stock_code.setObjectName("input_stock_code")
        self.btn_update_k_data = QtWidgets.QPushButton(self.by_stock_code)
        self.btn_update_k_data.setGeometry(QtCore.QRect(210, 20, 101, 23))
        self.btn_update_k_data.setObjectName("btn_update_k_data")
        self.btn_update_statement = QtWidgets.QPushButton(self.by_stock_code)
        self.btn_update_statement.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.btn_update_statement.setObjectName("btn_update_statement")
        self.rdb_bs = QtWidgets.QRadioButton(self.by_stock_code)
        self.rdb_bs.setGeometry(QtCore.QRect(130, 60, 101, 16))
        self.rdb_bs.setObjectName("rdb_bs")
        self.rdb_pl = QtWidgets.QRadioButton(self.by_stock_code)
        self.rdb_pl.setGeometry(QtCore.QRect(240, 60, 89, 16))
        self.rdb_pl.setCheckable(True)
        self.rdb_pl.setChecked(False)
        self.rdb_pl.setObjectName("rdb_pl")
        self.rdb_cash = QtWidgets.QRadioButton(self.by_stock_code)
        self.rdb_cash.setGeometry(QtCore.QRect(290, 60, 89, 16))
        self.rdb_cash.setObjectName("rdb_cash")
        self.btn_draw = QtWidgets.QPushButton(self.by_stock_code)
        self.btn_draw.setGeometry(QtCore.QRect(610, 20, 41, 23))
        self.btn_draw.setObjectName("btn_draw")
        self.lbl_close_price = QtWidgets.QLabel(self.by_stock_code)
        self.lbl_close_price.setGeometry(QtCore.QRect(420, 60, 71, 20))
        self.lbl_close_price.setObjectName("lbl_close_price")
        self.output_close_price = QtWidgets.QLabel(self.by_stock_code)
        self.output_close_price.setGeometry(QtCore.QRect(500, 60, 54, 20))
        self.output_close_price.setObjectName("output_close_price")
        self.btn_search_k_data = QtWidgets.QPushButton(self.by_stock_code)
        self.btn_search_k_data.setGeometry(QtCore.QRect(570, 60, 75, 23))
        self.btn_search_k_data.setObjectName("btn_search_k_data")
        self.by_stock_list = QtWidgets.QGroupBox(self.centralwidget)
        self.by_stock_list.setGeometry(QtCore.QRect(10, 120, 301, 91))
        self.by_stock_list.setObjectName("by_stock_list")
        self.btn_update_sz50 = QtWidgets.QPushButton(self.by_stock_list)
        self.btn_update_sz50.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.btn_update_sz50.setObjectName("btn_update_sz50")
        self.btn_update_hs300 = QtWidgets.QPushButton(self.by_stock_list)
        self.btn_update_hs300.setGeometry(QtCore.QRect(100, 20, 91, 23))
        self.btn_update_hs300.setObjectName("btn_update_hs300")
        self.btn_update_zz500 = QtWidgets.QPushButton(self.by_stock_list)
        self.btn_update_zz500.setGeometry(QtCore.QRect(200, 20, 91, 23))
        self.btn_update_zz500.setObjectName("btn_update_zz500")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 380, 681, 271))
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setObjectName("textEdit")
        self.for_all_stock = QtWidgets.QGroupBox(self.centralwidget)
        self.for_all_stock.setGeometry(QtCore.QRect(10, 220, 301, 151))
        self.for_all_stock.setCheckable(False)
        self.for_all_stock.setObjectName("for_all_stock")
        self.btn_update_divi_data = QtWidgets.QPushButton(self.for_all_stock)
        self.btn_update_divi_data.setGeometry(QtCore.QRect(10, 20, 141, 23))
        self.btn_update_divi_data.setObjectName("btn_update_divi_data")
        self.input_from_date = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.input_from_date.setGeometry(QtCore.QRect(420, 30, 91, 22))
        self.input_from_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.input_from_date.setCalendarPopup(True)
        self.input_from_date.setObjectName("input_from_date")
        self.input_to_date = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.input_to_date.setGeometry(QtCore.QRect(520, 30, 91, 22))
        self.input_to_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.input_to_date.setCalendarPopup(True)
        self.input_to_date.setObjectName("input_to_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.by_stock_code.setTitle(_translate("MainWindow", "By Stock Code"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_update_k_data.setText(_translate("MainWindow", "Update K data"))
        self.btn_update_statement.setText(_translate("MainWindow", "Update Statement"))
        self.rdb_bs.setText(_translate("MainWindow", "Balance Sheet"))
        self.rdb_pl.setWhatsThis(_translate("MainWindow", "P&L Statement"))
        self.rdb_pl.setText(_translate("MainWindow", "P&&L"))
        self.rdb_cash.setText(_translate("MainWindow", "Cash Flow"))
        self.btn_draw.setText(_translate("MainWindow", "Draw"))
        self.lbl_close_price.setText(_translate("MainWindow", "Close Price:"))
        self.output_close_price.setText(_translate("MainWindow", "0.0"))
        self.btn_search_k_data.setText(_translate("MainWindow", "Search"))
        self.by_stock_list.setTitle(_translate("MainWindow", "By Stock List"))
        self.btn_update_sz50.setText(_translate("MainWindow", "Update sz50"))
        self.btn_update_hs300.setText(_translate("MainWindow", "Update hs300"))
        self.btn_update_zz500.setText(_translate("MainWindow", "Update zz500"))
        self.for_all_stock.setTitle(_translate("MainWindow", "For All Stock"))
        self.btn_update_divi_data.setText(_translate("MainWindow", "Upate Dividend data"))
        self.input_from_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.input_to_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))

